/** Spanish translations of surah names, indexed by surah ID (1-114) */
export const SURAH_NAMES_ES: Record<number, string> = {
  1: "La Apertura",
  2: "La Vaca",
  3: "La Familia de Imrán",
  4: "Las Mujeres",
  5: "La Mesa Servida",
  6: "Los Rebaños",
  7: "Los Lugares Elevados",
  8: "El Botín",
  9: "El Arrepentimiento",
  10: "Jonás",
  11: "Hud",
  12: "José",
  13: "El Trueno",
  14: "Abraham",
  15: "Al-Hijr",
  16: "Las Abejas",
  17: "El Viaje Nocturno",
  18: "La Caverna",
  19: "María",
  20: "Ta-Ha",
  21: "Los Profetas",
  22: "La Peregrinación",
  23: "Los Creyentes",
  24: "La Luz",
  25: "El Criterio",
  26: "Los Poetas",
  27: "Las Hormigas",
  28: "El Relato",
  29: "La Araña",
  30: "Los Romanos",
  31: "Luqmán",
  32: "La Prosternación",
  33: "Los Aliados",
  34: "Saba",
  35: "El Creador",
  36: "Ya-Sin",
  37: "Los que se Alinean",
  38: "Sad",
  39: "Los Grupos",
  40: "El Perdonador",
  41: "Los Versículos Detallados",
  42: "La Consulta",
  43: "Los Ornamentos de Oro",
  44: "El Humo",
  45: "La Arrodillada",
  46: "Las Dunas",
  47: "Muhámmad",
  48: "La Victoria",
  49: "Las Habitaciones",
  50: "Qaf",
  51: "Los Vientos que Esparcen",
  52: "El Monte",
  53: "La Estrella",
  54: "La Luna",
  55: "El Misericordioso",
  56: "El Acontecimiento",
  57: "El Hierro",
  58: "La Discusión",
  59: "La Reunión",
  60: "La Examinada",
  61: "La Fila",
  62: "El Viernes",
  63: "Los Hipócritas",
  64: "El Desengaño",
  65: "El Divorcio",
  66: "La Prohibición",
  67: "La Soberanía",
  68: "El Cálamo",
  69: "La Inevitable",
  70: "Las Vías de Ascenso",
  71: "Noé",
  72: "Los Genios",
  73: "El Envuelto",
  74: "El Arropado",
  75: "La Resurrección",
  76: "El Ser Humano",
  77: "Los Enviados",
  78: "La Noticia",
  79: "Los que Arrancan",
  80: "Frunció el Ceño",
  81: "El Enrollamiento",
  82: "La Hendidura",
  83: "Los Defraudadores",
  84: "El Resquebrajamiento",
  85: "Las Constelaciones",
  86: "El Astro Nocturno",
  87: "El Altísimo",
  88: "La Abrumadora",
  89: "El Alba",
  90: "La Ciudad",
  91: "El Sol",
  92: "La Noche",
  93: "La Mañana",
  94: "La Expansión del Pecho",
  95: "La Higuera",
  96: "El Coágulo",
  97: "El Decreto",
  98: "La Evidencia",
  99: "El Terremoto",
  100: "Los Corceles",
  101: "La Calamidad",
  102: "La Rivalidad",
  103: "El Tiempo",
  104: "El Difamador",
  105: "El Elefante",
  106: "Los Coraichitas",
  107: "La Ayuda",
  108: "La Abundancia",
  109: "Los Incrédulos",
  110: "El Socorro",
  111: "Las Fibras",
  112: "La Unicidad",
  113: "El Amanecer",
  114: "La Humanidad",
};
